# Generated by Django 4.1 on 2023-02-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('System errors', 'System errors'), ('How to do that', 'How to do that'), ('Extremely urgent', 'Extremely urgent'), ('Suggestions or claims', 'Suggestions or claims')], max_length=50)),
                ('person', models.CharField(choices=[('Customer', 'Customer'), ('Employee', 'Employee')], max_length=50)),
                ('problem', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
