# Generated by Django 4.1 on 2023-02-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('', 'Choose person type'), ('Customer', 'Customer'), ('Employee', 'Employee')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='subject',
            field=models.CharField(choices=[('', 'Choose a subject'), ('System errors', 'System errors'), ('How to do that', 'How to do that'), ('Extremely urgent', 'Extremely urgent'), ('Suggestions or claims', 'Suggestions or claims')], max_length=50),
        ),
    ]
